function reportLink() {
    let domain = window.location.host;
    let path = window.location.pathname;
    let search = window.location.search;
    let link = domain+path+search;

    let email = "smart301@linistitul.ro?";
    let subject = "subject=Broken%20Link&";
    let body1 = "body=This%20email%20was%20autogenerated%20by%20the%20Smart%20301%20app.%0D%0APlease%20click%20send%20to%20submit%20your%20report.%0D%0A%0D%0A";
    let theLink = "Your%20link%3A "+link;
    let body2 = "%0D%0A%0D%0AThank%20you%20for%20using%20Smart%20301!";

    let compose = "mailto:"+email+subject+body1+theLink+body2;

    window.open(compose, "_blank");
}